import Head from 'next/head';
import Link from 'next/link';

import { createClient } from 'next-sanity';
import { useEffect, useState } from 'react';

// TODO: link this repo to Sanity.io

const client = createClient({
  projectId: 'gjsw9ksp',
  dataset: 'production',
  apiVersion: '2024-03-25',
  useCdn: false,
});

export default function Home() {
  const [loadedColors, setLoadedColors] = useState([]);

  useEffect(() => {
    const fetchData = async () => {
      const colors2 = await client.fetch(`*[_type == "color"]`);
      setLoadedColors(colors2);
      console.log(colors2);
    };

    fetchData();
  }, []);

  return (
    <div>
      <Head>
        <title>Colors!</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {loadedColors &&
        loadedColors.map((e: { name?: string; hex?: string; hexcode?: string }) => (
          <Link href={`/${e.name}`} key={e.name}>
            <h1>{e.name}</h1>
          </Link>
        ))}
    </div>
  );
}
