import Head from 'next/head';
import Link from 'next/link';

import colors from '../data/colors.json';

// TODO: link this repo to Sanity.io

export default function Home() {
  return (
    <div>
      <Head>
        <title>Colors!</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {colors &&
        colors.map((e: { name?: string; hex?: string; hexcode?: string }) => (
          <Link href={`/${e.name}`} key={e.name}>
            <h1>{e.name}</h1>
          </Link>
        ))}
    </div>
  );
}
