import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Colors!</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='w-full h-full'>local</div>
    </div>
  );
}
